import Layout from "./components/layout/Layout";
import "./globals.scss";
import store from "./store";
import { Providers } from "./redux/cart/providers";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        <Providers store={store}>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
